using System;
using System.Collections.Generic;
using System.IO;
using Code.ConfigExporter.Runtime;
using UnityEngine;

//This file is generated by code, do not modify!
namespace Code.Configuration
{
    public class ItemConfig
    {
		/*
		唯一ID
		*/
		public int Id { get; private set; }
		/*
		名称
		*/
		public string Name { get; private set; }
		/*
		道具
		*/
		public string Desc { get; private set; }
		/*
		2
		*/
		public int Type { get; private set; }
		public int FuncId { get; private set; }

        public static Dictionary<int, ItemConfig> D = null;
        public const string ConfigName = "ItemConfig";
        public static void Init(ConfigDeserializer configDeserializer, string configDirectory, Action onLoaded)
        {
            var file = configDirectory + ConfigName + ".bytes";
            if (!File.Exists(file))
            {
                Debug.LogError("Fail to load config : " + file);
                onLoaded?.Invoke();
                return;
            }

            var bytes = File.ReadAllBytes(file);
            configDeserializer.Init(bytes);

            var rows = configDeserializer.ReadInt();
            D = new Dictionary<int, ItemConfig>(rows);
            for (var r = 0; r < rows; r++)
            {
                var id = configDeserializer.ReadInt();
                D.Add(id, new ItemConfig
                {
                    Id = id,
					Name = configDeserializer.ReadString(),
					Desc = configDeserializer.ReadString(),
					Type = configDeserializer.ReadInt(),
					FuncId = configDeserializer.ReadInt(),

                });
            }
            onLoaded?.Invoke();
        }

        public static void Reset()
        {
            D = null;
        }
    }
}

